[package]
name = "mintara"
version = "1.0.0"
authors = []

[addresses]
mintara = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-framework-v1.0.0"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
